mod 'puppet/nginx'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'puppetlabs-docker', '3.2.0'
mod 'puppetlabs/apt'
mod 'puppetlabs/reboot'
mod 'puppetlabs/translate'
mod 'puppetlabs/powershell'
mod 'pltraining/dockeragent'
